#PremiumDomainRG by iVirus_
resumeTask: 300 #to not allow database disconnection
MySQL:
  Database: "PremiumDomainRG"
  Table: "PremiumDomainRG_Table"
  Username: "PremiumDomainRG"
  Password: "YourPassword"
  Host: "localhost"
  Port: 3306
  SSL: false

#Ignore this if run on Spigot
DomainPremium:
  - "premium.yourdomain.com"  #Only the first in the list will be shown in %domain_premium%
  - "premium.yourdomain.it"
DomainCrack: "mc.yourdomain.com"  #This has not any check, so you can join with "bye.yourdomain.com" or "ajniweu.yourdomain.com", this only replace %domain_crack%
JoinFromPremium: "&7You are premium, join through &c%domain_premium%"
JoinFromCrack: "&7You are from cracked client, join through &c%domain_crack%"
Confirm:
  - "&7&m----------------------------"
  - "&cAttention! &7Are you sure you want to convert this account"
  - "&7and make it &cpremium? &7You will never be able to go back!"
  - "&7To proceed re-type: &c/premium&7."
  - "&7&m----------------------------"
AlreadyPremium: "&cYou are already premium."
LogAgain: "Please log again from %domain_premium%"
CorrectUse: "&7Correct use: &4/premium"
Premium: